name: swire-fastapi
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - boto3>=1.34.72
    - langchain==0.1.0
    - pydantic==2.5.0
    - python-dotenv==1.0.0
    - PyYAML==6.0.1
    - requests==2.31.0