#!/usr/bin/env bash
set -euo pipefail

# Swire setup via CLI: validates/provisions Search + Storage + Foundry agent and writes local env file.

SUBSCRIPTION_NAME="${SUBSCRIPTION_NAME:-Microsoft Azure Sponsorship}"
RESOURCE_GROUP="${RESOURCE_GROUP:-rg-parvind.dutta-3699}"
LOCATION="${LOCATION:-eastus2}"

FOUNDRY_ACCOUNT="${FOUNDRY_ACCOUNT:-swirere-3699-resource}"
PROJECT_NAME="${PROJECT_NAME:-swirere-3699}"
PROJECT_ENDPOINT="${PROJECT_ENDPOINT:-https://swirere-3699-resource.services.ai.azure.com/api/projects/swirere-3699}"

SEARCH_SERVICE_NAME="${SEARCH_SERVICE_NAME:-swireopssrch03041557}"
SEARCH_SKU="${SEARCH_SKU:-basic}"
SEARCH_INDEX_NAME="${SEARCH_INDEX_NAME:-swire-operations-index}"

STORAGE_ACCOUNT_NAME="${STORAGE_ACCOUNT_NAME:-swireopsst03041603}"
STORAGE_SKU="${STORAGE_SKU:-Standard_LRS}"
STORAGE_CONTAINER="${STORAGE_CONTAINER:-operations-manuals}"

AGENT_NAME="${AGENT_NAME:-swire-ops-hr-agent}"
MODEL_DEPLOYMENT="${MODEL_DEPLOYMENT:-swire-gpt-4o}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env.azure.local"

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Missing required command: $1"
    exit 1
  }
}

need_cmd az
need_cmd jq
need_cmd curl

az account set --subscription "$SUBSCRIPTION_NAME"

if [[ "$(az group exists --name "$RESOURCE_GROUP")" != "true" ]]; then
  echo "Resource group $RESOURCE_GROUP not found. Creating in $LOCATION..."
  az group create --name "$RESOURCE_GROUP" --location "$LOCATION" >/dev/null
fi

if ! az cognitiveservices account show -g "$RESOURCE_GROUP" -n "$FOUNDRY_ACCOUNT" >/dev/null 2>&1; then
  echo "Foundry account $FOUNDRY_ACCOUNT not found in $RESOURCE_GROUP"
  exit 1
fi

if ! az search service show -g "$RESOURCE_GROUP" -n "$SEARCH_SERVICE_NAME" >/dev/null 2>&1; then
  echo "Search service $SEARCH_SERVICE_NAME not found. Creating..."
  az search service create \
    -g "$RESOURCE_GROUP" \
    -n "$SEARCH_SERVICE_NAME" \
    --sku "$SEARCH_SKU" \
    --partition-count 1 \
    --replica-count 1 \
    --location "$LOCATION" >/dev/null
fi

if ! az storage account show -g "$RESOURCE_GROUP" -n "$STORAGE_ACCOUNT_NAME" >/dev/null 2>&1; then
  echo "Storage account $STORAGE_ACCOUNT_NAME not found. Creating..."
  az storage account create \
    -g "$RESOURCE_GROUP" \
    -n "$STORAGE_ACCOUNT_NAME" \
    --sku "$STORAGE_SKU" \
    --kind StorageV2 \
    --location "$LOCATION" >/dev/null
fi

STORAGE_KEY="$(az storage account keys list -g "$RESOURCE_GROUP" -n "$STORAGE_ACCOUNT_NAME" --query '[0].value' -o tsv)"
az storage container create \
  --name "$STORAGE_CONTAINER" \
  --account-name "$STORAGE_ACCOUNT_NAME" \
  --account-key "$STORAGE_KEY" >/dev/null

SEARCH_ENDPOINT="https://${SEARCH_SERVICE_NAME}.search.windows.net"
SEARCH_ADMIN_KEY="$(az search admin-key show -g "$RESOURCE_GROUP" --service-name "$SEARCH_SERVICE_NAME" --query primaryKey -o tsv)"

STORAGE_CONNECTION_STRING="$(az storage account show-connection-string -g "$RESOURCE_GROUP" -n "$STORAGE_ACCOUNT_NAME" --query connectionString -o tsv)"
OPENAI_KEY="$(az cognitiveservices account keys list -g "$RESOURCE_GROUP" -n "$FOUNDRY_ACCOUNT" --query key1 -o tsv)"
OPENAI_ENDPOINT="https://${FOUNDRY_ACCOUNT}.openai.azure.com/"

q() {
  printf "%q" "$1"
}

cat > "$ENV_FILE" <<VARS
# Generated by scripts/swire_setup_cli.sh
AZURE_OPENAI_KEY=$(q "$OPENAI_KEY")
AZURE_OPENAI_ENDPOINT=$(q "$OPENAI_ENDPOINT")
AZURE_OPENAI_DEPLOYMENT=$(q "$MODEL_DEPLOYMENT")
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=swire-embeddings-3-small
AZURE_OPENAI_EMBEDDING_DIM=1536

AZURE_SEARCH_ENDPOINT=$(q "$SEARCH_ENDPOINT")
AZURE_SEARCH_KEY=$(q "$SEARCH_ADMIN_KEY")
AZURE_SEARCH_INDEX=$(q "$SEARCH_INDEX_NAME")

AZURE_STORAGE_CONNECTION_STRING=$(q "$STORAGE_CONNECTION_STRING")
AZURE_STORAGE_CONTAINER=$(q "$STORAGE_CONTAINER")

PROJECT_ENDPOINT=$(q "$PROJECT_ENDPOINT")
AGENT_NAME=$(q "$AGENT_NAME")
DATA_PATH=$(q "${ROOT_DIR}/enterprise-data")
VARS

TOKEN="$(az account get-access-token --resource https://ai.azure.com --query accessToken -o tsv)"
AGENTS_JSON="$(curl -sS -H "Authorization: Bearer $TOKEN" "${PROJECT_ENDPOINT}/agents?api-version=v1")"

if echo "$AGENTS_JSON" | jq -e --arg agent "$AGENT_NAME" '.data[]? | select(.id == $agent or .name == $agent)' >/dev/null; then
  echo "Agent already exists: $AGENT_NAME"
else
  echo "Creating Foundry agent: $AGENT_NAME"
  CREATE_PAYLOAD=$(jq -n \
    --arg name "$AGENT_NAME" \
    --arg model "$MODEL_DEPLOYMENT" \
    '{name:$name, definition:{kind:"prompt", model:$model, instructions:"You are Swire Operations and HR assistant. Answer using indexed department policies first, then provide concise operational next steps.", tools:[]}}')

  curl -sS -X POST \
    -H "Authorization: Bearer $TOKEN" \
    -H "Content-Type: application/json" \
    "${PROJECT_ENDPOINT}/agents?api-version=v1" \
    -d "$CREATE_PAYLOAD" | jq '{id,name,version:.versions.latest.version}'
fi

echo "Setup complete."
echo "Generated env file: $ENV_FILE"
echo "Next: source .env.azure.local && scripts/swire_refresh_kb_cli.sh"
